# Generated by Django 4.0.1 on 2022-02-28 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_members_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
