# Generated by Django 4.0.1 on 2022-02-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
