# Generated by Django 4.0.1 on 2022-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0003_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to='profilepics'),
        ),
    ]
