# Generated by Django 4.0.1 on 2022-02-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0003_society_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='society',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='academic_adventure.society'),
            preserve_default=False,
        ),
    ]
