# Generated by Django 4.0.1 on 2022-03-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0004_customuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(default='user.png', upload_to='profilepics')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='pic_inventory',
            field=models.ManyToManyField(blank=True, to='academic_adventure.Image'),
        ),
    ]
