# Generated by Django 4.0.1 on 2022-02-23 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0004_event_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='society',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic_adventure.society'),
        ),
        migrations.AlterField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
