# Generated by Django 4.0.1 on 2022-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0005_alter_customuser_athleticism_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ath_xp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='intel_xp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='soc_xp',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='athleticism',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sociability',
            field=models.IntegerField(default=0),
        ),
    ]
