# Generated by Django 4.0.1 on 2022-03-17 13:11

from django.db import migrations, models

"""
This Migration will alter the code view

This will make it so that the code field is now maximum of 100,
It will then also ensures it must be unique
"""
class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0006_remove_customuser_ath_xp_remove_customuser_intel_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
