# Generated by Django 4.0.1 on 2022-02-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0006_alter_event_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='society',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_adventure.society'),
        ),
    ]
