# Generated by Django 4.0.1 on 2022-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0007_alter_event_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
