# Generated by Django 4.0.1 on 2022-03-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0006_alter_image_name'),
        ('academic_adventure', '0007_alter_event_code'),
    ]

    operations = [
    ]
