# Generated by Django 4.0.1 on 2022-03-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0008_merge_0006_alter_image_name_0007_alter_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='icon',
            field=models.ImageField(default='user.png', upload_to='profilepics'),
        ),
        migrations.AddField(
            model_name='image',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='rarity',
            field=models.CharField(default='user.png', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pic_inventory',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_pic_inventory_created', to='academic_adventure.Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic_adventure.image'),
        ),
    ]
