# Generated by Django 4.0.1 on 2022-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0010_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='user.png', max_length=40),
        ),
    ]
