# Generated by Django 4.0.1 on 2022-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_adventure', '0011_alter_image_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], max_length=40),
        ),
    ]
