name: Linter

on:
   push:
      branches: [main]
   pull_request:
      branches: [main]

jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         - uses: actions/checkout@v2
         - name: Super-Linter
           uses: github/super-linter@v4.9.0
        
        

